environment:
  nodejs_version: "9"
  NODE_ENV: production

install:
  - ps: Install-Product node $env:nodejs_version
  - yarn install

build_script:
  - yarn run-prod

test_script:
  - yarn test

cache:
  - "%LOCALAPPDATA%\\Yarn"
