version: '2.1'

services:
  web:
    build: .
    restart: always
    ports:
      - "3003:3003"
    depends_on:
      - postgres
    environment:
      - NODE_ENV=production

  postgres:
    image: postgres:9.5
    restart: always
    volumes:
      - ./backend/postgres-init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_DB=docker
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
