version: '2.1'

services:
  web:
    build:
      context: .
      args:
        PORT: ${PORT}
    restart: always
    ports:
      - "$PORT:$PORT"
    depends_on:
      - postgres
    environment:
      - PORT=${PORT}

  postgres:
    image: postgres:9.5
    restart: always
    volumes:
      - ./backend/postgres-init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
